
import { Militar, PostoPatente, QuadroMilitar, TipoSanguineo, Sexo } from "@/types";

export const mockMilitares: Militar[] = [
  {
    id: "1",
    quadro: "QOE",
    posto: "Major",
    nomeCompleto: "João da Silva Santos",
    nomeGuerra: "SANTOS",
    foto: "",
    dataNascimento: "1980-05-15",
    dataInclusao: "2000-03-01",
    dataUltimaPromocao: "2020-01-10",
    situacao: "ativo",
    email: "joao.santos@cbm.pi.gov.br",
    tipoSanguineo: "A+",
    sexo: "Masculino"
  },
  {
    id: "2",
    quadro: "QOE",
    posto: "Major",
    nomeCompleto: "Maria Oliveira Costa",
    nomeGuerra: "COSTA",
    foto: "",
    dataNascimento: "1985-07-22",
    dataInclusao: "2005-06-15",
    dataUltimaPromocao: "2019-12-05",
    situacao: "ativo",
    email: "maria.costa@cbm.pi.gov.br",
    tipoSanguineo: "O-",
    sexo: "Feminino"
  },
  {
    id: "3",
    quadro: "QOEM",
    posto: "Coronel",
    nomeCompleto: "Pedro Alves Ferreira",
    nomeGuerra: "FERREIRA",
    foto: "",
    dataNascimento: "1975-03-28",
    dataInclusao: "1995-02-10",
    dataUltimaPromocao: "2018-06-20",
    situacao: "ativo",
    email: "pedro.ferreira@cbm.pi.gov.br",
    tipoSanguineo: "B+",
    sexo: "Masculino"
  },
  {
    id: "4",
    quadro: "QORR",
    posto: "Tenente-Coronel",
    nomeCompleto: "Carlos Mendes Sousa",
    nomeGuerra: "MENDES",
    foto: "",
    dataNascimento: "1970-11-05",
    dataInclusao: "1992-04-30",
    dataUltimaPromocao: "2015-09-15",
    situacao: "inativo",
    email: "carlos.mendes@cbm.pi.gov.br",
    tipoSanguineo: "AB-",
    sexo: "Masculino"
  },
  {
    id: "5",
    quadro: "QPBM",
    posto: "1º Sargento",
    nomeCompleto: "Ana Paula Ribeiro",
    nomeGuerra: "RIBEIRO",
    foto: "",
    dataNascimento: "1988-12-03",
    dataInclusao: "2010-08-20",
    dataUltimaPromocao: "2022-03-01",
    situacao: "ativo",
    email: "ana.ribeiro@cbm.pi.gov.br",
    tipoSanguineo: "A-",
    sexo: "Feminino"
  },
  {
    id: "6",
    quadro: "QPRR",
    posto: "Subtenente",
    nomeCompleto: "José Carlos Lima",
    nomeGuerra: "LIMA",
    foto: "",
    dataNascimento: "1965-09-18",
    dataInclusao: "1985-05-10",
    dataUltimaPromocao: "2010-11-20",
    situacao: "inativo",
    email: "jose.lima@cbm.pi.gov.br",
    tipoSanguineo: "O+",
    sexo: "Masculino"
  }
];
