// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adpornkhdtryvtnehqah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkcG9ybmtoZHRyeXZ0bmVocWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzYzOTEsImV4cCI6MjA2MTExMjM5MX0.spMFZY3j1CYOOft53mOBsfMx9Jzc2QCfnO3A17f9Rk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);