
import { Militar } from "@/types";

// Mock militares data
export const mockMilitares: Militar[] = [
  {
    id: "1",
    nomeCompleto: "José Erisman de Sousa",
    nome: "José Erisman de Sousa",
    nomeGuerra: "Erisman",
    quadro: "QOE",
    posto: "Major",
    foto: "https://api.dicebear.com/7.x/initials/svg?seed=Erisman",
    dataNascimento: "1980-05-12",
    dataInclusao: "2000-03-01",
    dataUltimaPromocao: "2022-12-23",
    situacao: "ativo",
    email: "erisman@cbmepi.gov.br",
    tipoSanguineo: "A+",
    sexo: "Masculino",
    unidade: "Quartel Central"
  },
  {
    id: "2",
    nomeCompleto: "Flaubert Rocha Vieira",
    nome: "Flaubert Rocha Vieira",
    nomeGuerra: "Flaubert",
    quadro: "QOE",
    posto: "Major",
    foto: "https://api.dicebear.com/7.x/initials/svg?seed=Flaubert",
    dataNascimento: "1982-07-23",
    dataInclusao: "2002-01-15",
    dataUltimaPromocao: "2023-07-18",
    situacao: "ativo",
    email: "flaubert@cbmepi.gov.br",
    tipoSanguineo: "O+",
    sexo: "Masculino",
    unidade: "Quartel Central"
  },
  {
    id: "3",
    nomeCompleto: "Roberto Carlos Sousa",
    nome: "Roberto Carlos Sousa",
    nomeGuerra: "Roberto",
    quadro: "QOEM",
    posto: "Coronel",
    foto: "https://api.dicebear.com/7.x/initials/svg?seed=Roberto",
    dataNascimento: "1975-03-10",
    dataInclusao: "1995-01-10",
    dataUltimaPromocao: "2020-06-15",
    situacao: "ativo",
    email: "roberto@cbmepi.gov.br",
    tipoSanguineo: "B+",
    sexo: "Masculino",
    unidade: "Comando Geral"
  },
  {
    id: "4",
    nomeCompleto: "Carlos Alberto Pereira",
    nome: "Carlos Alberto Pereira",
    nomeGuerra: "Alberto",
    quadro: "QORR",
    posto: "Tenente-Coronel",
    foto: "https://api.dicebear.com/7.x/initials/svg?seed=Alberto",
    dataNascimento: "1968-11-20",
    dataInclusao: "1990-02-22",
    dataUltimaPromocao: "2018-04-10",
    situacao: "inativo",
    email: "alberto@cbmepi.gov.br",
    tipoSanguineo: "AB+",
    sexo: "Masculino",
    unidade: "Reserva"
  },
  {
    id: "5",
    nomeCompleto: "Ana Maria da Silva",
    nome: "Ana Maria da Silva",
    nomeGuerra: "Ana",
    quadro: "QPBM",
    posto: "1º Sargento",
    foto: "https://api.dicebear.com/7.x/initials/svg?seed=Ana",
    dataNascimento: "1985-09-05",
    dataInclusao: "2005-03-15",
    dataUltimaPromocao: "2021-08-12",
    situacao: "ativo",
    email: "ana@cbmepi.gov.br",
    tipoSanguineo: "A-",
    sexo: "Feminino",
    unidade: "1º BBM"
  },
  {
    id: "6",
    nomeCompleto: "João Paulo Ferreira",
    nome: "João Paulo Ferreira",
    nomeGuerra: "João",
    quadro: "QPRR",
    posto: "Subtenente",
    foto: "https://api.dicebear.com/7.x/initials/svg?seed=João",
    dataNascimento: "1970-02-28",
    dataInclusao: "1990-06-10",
    dataUltimaPromocao: "2015-10-05",
    situacao: "inativo",
    email: "joao@cbmepi.gov.br",
    tipoSanguineo: "O-",
    sexo: "Masculino",
    unidade: "Reserva"
  }
];
